A = int(input())
B = int(input())
C = int(input())
D = int(input())
E = int(input())
F = float(input())
G = float(input())
H = float(input())
I = float(input())
J = float(input())
print(int((A*F)+(B*G)+(C*H)+(D*I)+(E*J)))